"""Canonical EQR autoresearch package."""
# pyright: reportMissingImports=false, reportUnknownVariableType=false

from .data_contracts import ARTIFACT_CONTRACTS, CONTRACTS_BY_NAME
from .ledger import IllegalStateTransition, JobLedger, JobState, LedgerConfig, SQLiteJobLedger
from .path_resolver import ResolvedArtifact, resolve_data_paths
from .panel import build_forward_returns, build_monthly_universe, build_panel, validate_labels
from .pit import CCMLinkResolver, CRSPNameResolver, EntityMapper, IBESLinkResolver
from .scheduler import (
    BudgetPolicyResult,
    ExecutionResult,
    ProposalResult,
    adaptive_budget,
    batch_propose,
    claim_job,
    dead_letter_job,
    execute_job,
    export_ledger,
    list_dead_letter_jobs,
    propose_job,
    retry_job,
    run_batch,
)
from .schemas import (
    ARTIFACT_PROVENANCE_COLUMNS,
    EQR_IDENTIFIER_COLUMNS,
    EQR_PANEL_KEY_COLUMNS,
    EQR_PANEL_REQUIRED_COLUMNS,
    EXPERIMENT_ARTIFACT_REQUIRED_FILES,
    EXPERIMENT_FEATURE_IMPORTANCE_REQUIRED_COLUMNS,
    EXPERIMENT_MANIFEST_REQUIRED_FIELDS,
    EXPERIMENT_PREDICTIONS_REQUIRED_COLUMNS,
    MACRO_FEATURE_PREFIX,
    MODEL_DATASET_KEY_COLUMNS,
    MODEL_DATASET_REQUIRED_COLUMNS,
    read_dataset,
    require_columns,
    require_unique_key,
    summarize_dataframe,
    write_dataset,
)

__all__ = [
    "ARTIFACT_CONTRACTS",
    "ARTIFACT_PROVENANCE_COLUMNS",
    "BudgetPolicyResult",
    "CCMLinkResolver",
    "CONTRACTS_BY_NAME",
    "CRSPNameResolver",
    "EntityMapper",
    "EQR_IDENTIFIER_COLUMNS",
    "EQR_PANEL_KEY_COLUMNS",
    "EQR_PANEL_REQUIRED_COLUMNS",
    "EXPERIMENT_ARTIFACT_REQUIRED_FILES",
    "EXPERIMENT_FEATURE_IMPORTANCE_REQUIRED_COLUMNS",
    "EXPERIMENT_MANIFEST_REQUIRED_FIELDS",
    "EXPERIMENT_PREDICTIONS_REQUIRED_COLUMNS",
    "ExecutionResult",
    "IBESLinkResolver",
    "IllegalStateTransition",
    "JobLedger",
    "JobState",
    "LedgerConfig",
    "MACRO_FEATURE_PREFIX",
    "MODEL_DATASET_KEY_COLUMNS",
    "MODEL_DATASET_REQUIRED_COLUMNS",
    "ProposalResult",
    "ResolvedArtifact",
    "SQLiteJobLedger",
    "adaptive_budget",
    "batch_propose",
    "build_forward_returns",
    "build_monthly_universe",
    "build_panel",
    "claim_job",
    "dead_letter_job",
    "execute_job",
    "export_ledger",
    "list_dead_letter_jobs",
    "propose_job",
    "read_dataset",
    "require_columns",
    "require_unique_key",
    "resolve_data_paths",
    "retry_job",
    "run_batch",
    "summarize_dataframe",
    "validate_labels",
    "write_dataset",
]
